### ISSUE TITLE
Theme error

### ISSUE THREAD

**Issue by codyconley** [amanatron/Maestoso#1]
<img width="277" alt="Screen Shot 2021-03-28 at 11 30 59 PM" src="https://user-images.githubusercontent.com/80540250/112857034-6fbf0200-907e-11eb-9e90-3a539b62ed86.png">

I finally got the program running but now I can't use themes.  This is the message that I get when I try to import a theme.

**Comment by amanatron** [comment]
Hi, so sorry for the delayed response. It seems like you're missing some modules. Do you have all the necessary dependencies installed? 

On the other hand, do you have an empty folder titled "PNG_EXPORTS" in your root directory?

**Comment by codyconley** [comment]
> Hi, so sorry for the delayed response. It seems like you're missing some modules. Do you have all the necessary dependencies installed? 
> 
> On the other hand, do you have an empty folder titled "PNG_EXPORTS" in your root directory? 

I had everything installed from the GitHub source code download but I don't think I had that file. Thanks for helping!

**Comment by amanatron** [comment]
> > Hi, so sorry for the delayed response. It seems like you're missing some modules. Do you have all the necessary dependencies installed? 
> > 
> > On the other hand, do you have an empty folder titled "PNG_EXPORTS" in your root directory? 
> 
> I had everything installed from the GitHub source code download but I don't think I had that file. Thanks for helping! 

Let me know if that resolves all your problems! Hope you enjoy it :)

**Comment by amanatron** [comment]
I'm closing this issue now - assuming all your problems were sorted post the addition of "PNG_EXPORTS" in your root dir.
