### ISSUE TITLE
Requirements/Modules to run

### ISSUE THREAD

**Issue by Enderchief** [amanatron/Maestoso#2]
This is a suggestion.
Have a `requirements.txt` for the project.
For many, they do not want to go through the hassle of looking through the code or rerunning the program multiple time in order to find what is needed to be installed. Even looking at the code, some modules have different names in code compared to on pip.
Thanks for listening.

**Comment by kyle-silver** [comment]
Agreed. I might work on a PR for this, but for @amanatron you can always run 

```console
$ pip freeze > requirements.txt
```

to generate a rudimentary file (assuming you're using pip) but you'll probably want to trim it down because that'll give you every package installed on your system

**Comment by amanatron** [comment]
I'll add one right away! Thank you so much for the suggestion. And really sorry for the hassle - I'll try my best to get the program working for you!

**Comment by amanatron** [comment]
The file has been modified and added to the root directory.
